routes:
  /: home
  /gioi-thieu/: about
  /dich-vu/: services
  /lien-he/: contact


collections:
  /bai-viet/:
    permalink: '/bai-viet/{slug}/'
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
  